version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: npm install

  sonarCloudAnalysis:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: Install & Run SonarScanner Analysis 
          command: |
              export SONAR_SCANNER_VERSION=7.0.2.4839
              export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
              curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
              unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
              export PATH=$SONAR_SCANNER_HOME/bin:$PATH
              export SONAR_SCANNER_OPTS="-server"
              ls $SONAR_SCANNER_HOME/bin #check if sonar-scanner binary is present here
              sonar-scanner -Dsonar.organization=sid14581 -Dsonar.projectKey=sid14581_demo_3_circleci_pipeline -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=$SONAR_TOKEN
  
  build_scan_push_docker_image:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker Image 
          command: docker build -t $DOCKERHUB_USERNAME/circlecipipelinenpm:latest . 
      - run:
          name: Checking Image locally
          command: docker images
      - run:
          name: Push Image to DockerHub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push "$DOCKERHUB_USERNAME/circlecipipelinenpm:1"
      - run: 
          name: Trivy Scan
          command: | 
            docker pull aquasec/trivy:latest
            docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest --severity HIGH,CRITICAL image $DOCKERHUB_USERNAME/circlecipipelinenpm:1
        

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - install_dependencies
      - sonarCloudAnalysis:
          requires:
            - install_dependencies
      - build_scan_push_docker_image:
          requires:
            - sonarCloudAnalysis

      