apiVersion: apps/v1
kind: Deployment
metadata:
  name: iquant-app-deployment
  labels:
    app: iquant-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iquant-app
  template:
    metadata:
      labels:
        app: iquant-app
    spec:
      containers:
      - name: iquant-app
        image: sid716/circlecipipelinenpm:2.0 
        ports:
        - containerPort: 3000

